services/web/app/users/forms.py
from flask import request
from flask_login import current_user
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, HiddenField, TextAreaField, \
    FileField
from wtforms.validators import DataRequired, ValidationError, Email, Length, EqualTo, Optional

from app.forms import AppForm
from app.models import User, Role


class SearchForm(AppForm):
    search = StringField('Поиск')
    submit = SubmitField('Искать')

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)


class RegistrationForm(AppForm):
    first_name = StringField('Имя', validators=[DataRequired(message='Поле не должно быть пустым')])
    middle_name = StringField('Отчество', validators=[DataRequired(message='Поле не должно быть пустым')])
    second_name = StringField('Фамилия', validators=[DataRequired(message='Поле не должно быть пустым')])
    email = StringField('Email', validators=[
        DataRequired(message='Поле не должно быть пустым'),
        Email(message='Не корректный email')])
    role = SelectField("Роль", choices=[
        (Role.ROLE_EMPLOYEE, "Сотрудник"),
        (Role.ROLE_SECRETARY, "Секретарь"),
        (Role.ROLE_ADMIN, "Администратор")
    ])
    vector = TextAreaField('Вектор')
    password = PasswordField('Пароль')
    password_repeat = PasswordField('Повтор пароля', validators=[
        EqualTo('password', message='Поле должно совпадать с полем "Пароль"')])
    avatar = FileField('Фотография', validators=[
        FileAllowed(['jpg', 'png', 'jpeg'], 'Доступны только форматы: jpg, png, jpeg')
    ])
    send_flag = BooleanField('Отправлять уведомления', default=False)
    submit = SubmitField('Добавить')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Данный Email уже занят')

    def validate_password(self, password):
        if Role.ROLE_EMPLOYEE != self.role.data and len(password.data) < 8:
            raise ValidationError('Пользователь с ролью "Администратор" или "Секретарь" должен иметь пароль, '
                                  'который должен содержать от 8 до 50 символов')


class EditUserForm(AppForm):
    id = HiddenField('id')
    first_name = StringField('Имя', validators=[DataRequired(message='Поле не должно быть пустым')])
    middle_name = StringField('Отчество', validators=[DataRequired(message='Поле не должно быть пустым')])
    second_name = StringField('Фамилия', validators=[DataRequired(message='Поле не должно быть пустым')])
    email = StringField('Email', validators=[DataRequired(message='Поле не должно быть пустым'), Email()])
    role = SelectField("Роль", choices=[
        (Role.ROLE_EMPLOYEE, "Сотрудник"),
        (Role.ROLE_SECRETARY, "Секретарь"),
        (Role.ROLE_ADMIN, "Администратор")
    ])
    vector = TextAreaField('Вектор')
    avatar_image = FileField('Фотография', validators=[
        FileAllowed(['jpg', 'png', 'jpeg'], 'Доступны только форматы: jpg, png, jpeg')
    ])
    send_flag = BooleanField('Отправлять уведомления', default=False)
    submit = SubmitField('Изменить')

    def __init__(self, original_email, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.original_email = original_email
        if current_user.has_role(Role.ROLE_SECRETARY):
            del self.role

    def validate_email(self, email):
        if email.data != self.original_email:
            user = User.query.filter_by(email=self.email.data).first()
            if user is not None:
                raise ValidationError('Данный Email уже занят')


class PasswordForm(AppForm):
    password = PasswordField('Пароль', validators=[
        Length(min=8, max=50, message='Поле должно содержать от %(min)d до %(max)d символов')])
    password_repeat = PasswordField('Повтор пароля', validators=[
        EqualTo('password', message='Поле должно совпадать с полем "Пароль"')])
    submit = SubmitField('Изменить')


class UserImagesFiles(AppForm):
    file_1 = FileField('Изображение 1', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    file_2 = FileField('Изображение 2', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    file_3 = FileField('Изображение 3', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    file_4 = FileField('Изображение 4', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    file_5 = FileField('Изображение 5', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    file_6 = FileField('Изображение 6', validators=[
        FileRequired('Требуется изображение'),
        FileAllowed(['jpg', 'png'], 'Доступны только форматы: jpg, png')
    ])
    submit = SubmitField('Изменить')

services/web/app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

services/web/app/users/routes.py
import os
import uuid

from app import db
from app.auth.decorators import role_required
from app.models import User, Role
from app.users import bp
from app.users.client import get_vector_user
from app.users.forms import SearchForm, RegistrationForm, EditUserForm, UserImagesFiles, PasswordForm
from flask import render_template, request, current_app, flash, redirect, url_for, abort
from flask_login import current_user
from sqlalchemy import or_


@bp.route('/users', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def index():
    page = request.args.get('page', 1, type=int)
    form = SearchForm()
    users = User.query
    if form.validate() and len(form.search.data):
        users = users.filter(
            or_(
                User.second_name.ilike('{}%'.format(form.search.data)),
                User.first_name.ilike('{}%'.format(form.search.data)),
                User.middle_name.ilike('{}%'.format(form.search.data)),
            )
        )
    users = users.order_by(User.id).paginate(page, current_app.config['USERS_PER_PAGE'], False)
    return render_template('users/users.html', users=users, form=form)


@bp.route('/user/add', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN])
def user_add():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            middle_name=form.middle_name.data,
            second_name=form.second_name.data,
            send_flag=form.send_flag.data,
            vector=form.vector.data
        )
        if form.role.data != Role.ROLE_EMPLOYEE:
            user.set_password(form.password.data)
        user.set_role(form.role.data)
        if form.avatar.data:
            file = form.avatar.data
            user.avatar = str(uuid.uuid4()) + os.path.splitext(file.filename)[1]
            path = os.path.join(current_app.config['STATIC_DIR'], current_app.config['UPLOAD_AVATAR_FOLDER'])
            file.save(os.path.join(path, user.avatar))
        db.session.add(user)
        db.session.commit()
        flash('Пользователь добавлен', current_app.config['SUCCESS_FLASH'])
        return redirect(url_for('users.index'))
    return render_template('users/user_add.html', form=form)


@bp.route('/user/<int:id>/edit', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def user_edit(id):
    if not current_user.has_role(Role.ROLE_ADMIN) and current_user.id != id:
        abort(403)
    user = User.query.get_or_404(id)
    form = EditUserForm(user.email)
    if request.method == 'GET':
        form.full(user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.first_name = form.first_name.data
        user.middle_name = form.middle_name.data
        user.second_name = form.second_name.data
        user.send_flag = form.send_flag.data
        user.vector = form.vector.data
        if form.role.data != user.get_role().name and not current_user.has_role(Role.ROLE_SECRETARY):
            user.set_role(form.role.data)
        if form.avatar_image.data:
            file = form.avatar_image.data
            user.avatar = str(uuid.uuid4()) + os.path.splitext(file.filename)[1]
            path = os.path.join(current_app.config['STATIC_DIR'], current_app.config['UPLOAD_AVATAR_FOLDER'])
            file.save(os.path.join(path, user.avatar))
        db.session.commit()
        form.full(user)
        flash('Пользователь изменен', current_app.config['SUCCESS_FLASH'])
    return render_template('users/user_edit.html', form=form)


@bp.route('/user/<int:id>/password-edit', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def user_password_edit(id):
    if not current_user.has_role(Role.ROLE_ADMIN) and current_user.id != id:
        abort(403)
    user = User.query.get_or_404(id)
    form = PasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Пароль изменен', current_app.config['SUCCESS_FLASH'])
    return render_template('users/user_password_edit.html', form=form)


@bp.route('/user/<int:id>', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def user_view(id):
    user = User.query.get_or_404(id)
    return render_template('users/user_view.html', user=user)


@bp.route('/user/<int:id>/delete', methods=['GET'])
@role_required([Role.ROLE_ADMIN])
def user_delete(id):
    user = User.query.get_or_404(id)
    if user.id == current_user.id:
        flash('Невозможно удалить себя самого', current_app.config['ERROR_FLASH'])
        return redirect(url_for('users.index'))
    db.session.delete(user)
    db.session.commit()
    flash('Пользователь {} удален'.format(id), current_app.config['SUCCESS_FLASH'])
    return redirect(url_for('users.index'))


@bp.route('/user/<int:id>/get-vector', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN])
def user_get_vector(id):
    user = User.query.get_or_404(id)
    form = UserImagesFiles()
    if form.validate_on_submit():
        data = {
            'id': str(id),
            'photos': [
                str(form.file_1.data.read()),
                str(form.file_2.data.read()),
                str(form.file_3.data.read()),
                str(form.file_4.data.read()),
                str(form.file_5.data.read()),
                str(form.file_6.data.read())
            ]
        }
        user.vector = get_vector_user(data)
        db.session.commit()
        flash('Вектор успешно получен', current_app.config['SUCCESS_FLASH'])
    return render_template('users/user_get_vector.html', form=form)

services/web/app/templates/users/user_add.html
{% extends "base_template.html" %}

{% block title %} Регистрация пользователей {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('users.index')}}">Пользователи</a></li>
                <li class="breadcrumb-item active" aria-current="page">Добавление пользователя</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/users/user_edit.html
{% extends "base_template.html" %}

{% block title %} Регистрация пользователей {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('users.index')}}">Пользователи</a></li>
                <li class="breadcrumb-item active" aria-current="page">Изменение пользователя</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/users/user_get_vector.html
{% extends "base_template.html" %}

{% block title %} Регистрация пользователей {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('users.index')}}">Пользователи</a></li>
                <li class="breadcrumb-item active" aria-current="page">Добавление вектора пользователя</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post"  enctype="multipart/form-data">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/users/user_password_edit.html
{% extends "base_template.html" %}

{% block title %} Регистрация пользователей {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('users.index')}}">Пользователи</a></li>
                <li class="breadcrumb-item active" aria-current="page">Изменение пароля</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/users/user_view.html
{% extends "base_template.html" %}

{% block title %} Регистрация пользователей {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('users.index')}}">Пользователи</a></li>
                <li class="breadcrumb-item active" aria-current="page">Просмотр пользователя</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="font-weight-bold">ID:</span> {{user.id}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Email:</span> {{user.email}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Имя:</span> {{user.first_name}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Фамилия:</span> {{user.second_name}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Отчество:</span> {{user.middle_name}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Рассылка:</span> {{'Да' if user.send_flag else 'Нет'}}</li>
                <li class="list-group-item"><span class="font-weight-bold">Вектор:</span> {{user.vector}}</li>
            </ul>
        </div>
        <div class="col">
            <div class="user-image">
                <img class="table-img" src="{{ url_for('static', filename=user.avatar_image) }}" alt="">
            </div>
        </div>
    </div>
{% endblock %}

services/web/app/templates/users/users.html
{% extends "base_template.html" %}

{% block title %} Пользователи {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Пользователи</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="clearfix">
        <div class="float-left">
            <form class="form-inline">
                <div class="form-group mr-1">
                    {% with placeholder = form.search.label.text %}
                        {{ form.search(class="form-control", placeholder=placeholder) }}
                    {% endwith %}
                </div>
                {{ form.submit(class="btn btn-primary") }}
            </form>
        </div>
        {% if current_user.get_role().name == 'ROLE_ADMIN' %}
            <a role="button" href="{{ url_for('users.user_add') }}" class="btn btn-success float-right">Добавить
                пользователя</a>
        {% endif %}
    </div>
    <div class="mt-4 text-center">
        <table class="table table-bordered table-hover">
            <thead>
            <tr class="table-active">
                <th scope="col">ID</th>
                <th scope="col">ФИО</th>
                <th scope="col">Email</th>
                <th scope="col">Права доступа</th>
                <th scope="col">Фото</th>
                <th scope="col">Рассылка</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users.items %}
                <tr>
                    <th scope="row">{{ user.id }}</th>
                    <td>{{ user.fio() }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.get_role_name_ru() }}</td>
                    <td><img class="table-img" src="{{ url_for('static', filename=user.avatar_image) }}" alt=""></td>
                    <td>{{'Да' if user.send_flag else 'Нет'}}</td>
                    <td class="action">
                        <a href="{{ url_for('users.user_view', id=user.id) }}"><i class="fas fa-eye"></i></a>
                        {% if current_user.get_role().name == 'ROLE_ADMIN' or current_user.id == user.id %}
                            <a href="{{ url_for('users.user_edit', id=user.id) }}"><i class="fas fa-edit"></i></a>
                            <a href="{{ url_for('users.user_password_edit', id=user.id) }}"><i class="fas fa-lock"></i></a>
                            <a href="{{ url_for('users.user_get_vector', id=user.id) }}"><i
                                    class="fas fa-smile"></i></a>
                            {% if current_user.id != user.id %}
                                <a href="{{ url_for('users.user_delete', id=user.id) }}"><i
                                        class="far fa-trash-alt"></i></a>
                            {% endif %}
                        {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="..." class="d-flex justify-content-center">
            <ul class="pagination">
                {% if users.has_prev %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('users.index', page = users.prev_num) }}"><<</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link"><<</span>
                    </li>
                {% endif %}
                {% if users.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('users.index', page = users.next_num) }}">>></a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">>></span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}