services/web/app/events/forms.py
from app.forms import AppForm
from app.models import User, Event
from flask import request
from wtforms import SubmitField, SelectField, TextAreaField, DateTimeField
from wtforms.ext.sqlalchemy.fields import QuerySelectField


class SearchDateTimeForm(AppForm):
    datetime_from = DateTimeField('От', format='%Y-%m-%dT%H:%M:%S')
    datetime_to = DateTimeField('До', format='%Y-%m-%dT%H:%M:%S')
    submit = SubmitField('Искать')

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchDateTimeForm, self).__init__(*args, **kwargs)
        first_event = Event.query.order_by(Event.timestamp.asc()).first()
        last_event = Event.query.order_by(Event.timestamp.desc()).first()
        if first_event and self.datetime_from.data is None:
            self.datetime_from.data = first_event.timestamp
        if last_event and self.datetime_to.data is None:
            self.datetime_to.data = last_event.timestamp


class EventsForm(AppForm):
    type = SelectField('Событие', choices=Event.EVENTS)
    timestamp = DateTimeField('Время', format='%Y-%m-%dT%H:%M:%S')
    link = TextAreaField('Ссылка')
    user = QuerySelectField(
        'Пользователь',
        query_factory=lambda: User.query,
        allow_blank=True,
        get_pk=lambda a: a.id
    )
    submit = SubmitField('Добавить')

    def __init__(self, edit_form=False, *args, **kwargs):
        super(EventsForm, self).__init__(*args, **kwargs)
        if edit_form:
            self.submit.label.text = 'Изменить'

services/web/app/events/__init__.py
from flask import Blueprint

bp = Blueprint('events', __name__)

from app.events import routes

services/web/app/events/routes.py
from app import db
from app.auth.decorators import role_required
from app.events import bp
from app.events.forms import SearchDateTimeForm, EventsForm
from app.models import Event, Role
from flask import request, redirect, url_for, render_template, flash, current_app


@bp.route('/events', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def events():
    page = request.args.get('page', 1, type=int)
    form = SearchDateTimeForm()
    events = Event.query
    if form.datetime_from.data is not None:
        events = events.filter(Event.timestamp >= form.datetime_from.data)
    if form.datetime_to.data is not None:
        events = events.filter(Event.timestamp <= form.datetime_to.data)
    events = events.order_by(Event.id).paginate(page, current_app.config['EVENTS_PER_PAGE'], False)
    return render_template('event/events.html', events=events, form=form)


@bp.route('/event/add', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN])
def event_add():
    form = EventsForm()
    if form.validate_on_submit():
        event = Event(
            type=form.type.data,
            timestamp=form.timestamp.data,
            user=form.user.data,
            link=form.link.data,
        )
        db.session.add(event)
        db.session.commit()
        flash('События добавлено', current_app.config['SUCCESS_FLASH'])
        return redirect(url_for('events.events'))
    return render_template('event/event_add.html', form=form)


@bp.route('/event/<int:id>/edit', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN])
def event_edit(id):
    event = Event.query.get_or_404(id)
    form = EventsForm(True)
    if request.method == 'GET':
        form.full(event)
    if form.validate_on_submit():
        event.type = form.type.data
        event.timestamp = form.timestamp.data
        event.user = form.user.data
        event.link = form.link.data
        db.session.commit()
        flash('Событие изменено', current_app.config['SUCCESS_FLASH'])
    return render_template('event/event_edit.html', form=form)


@bp.route('/event/<int:id>/delete', methods=['GET'])
@role_required([Role.ROLE_ADMIN])
def event_delete(id):
    event = Event.query.get_or_404(id)
    db.session.delete(event)
    db.session.commit()
    flash('Событие {} удалено'.format(id), current_app.config['SUCCESS_FLASH'])
    return redirect(url_for('events.events'))


@bp.route('/event/<int:id>', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def event_view(id):
    event = Event.query.get_or_404(id)
    return render_template('event/event_view.html', event=event)

services/web/app/templates/event/event_add.html
{% extends "base_template.html" %}

{% block title %} Добавление события {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('events.events')}}">События</a></li>
                <li class="breadcrumb-item active" aria-current="page">Добавление события</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/event/event_edit.html
{% extends "base_template.html" %}

{% block title %} Добавление события {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('events.events') }}">События</a></li>
                <li class="breadcrumb-item active" aria-current="page">Изменение события</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% include 'widgets/form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

services/web/app/templates/event/event_view.html
{% extends "base_template.html" %}

{% block title %} Просмотр события {{ event.id }} {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('events.events') }}">События</a></li>
                <li class="breadcrumb-item active" aria-current="page">Просмотр события</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><span class="font-weight-bold">ID:</span> {{ event.id }}</li>
            <li class="list-group-item"><span class="font-weight-bold">Пользователь:</span>
                {% if event.user %}
                    <a href="{{ url_for('users.user_view', id=event.user.id) }}">{{ event.user }}</a>
                {% else %}
                    Неизвестный пользователь
                {% endif %}
            </li>
            <li class="list-group-item"><span class="font-weight-bold">Событие:</span> {{ event.type_test() }}</li>
            <li class="list-group-item"><span
                    class="font-weight-bold">Время:</span> {{ event.timestamp.strftime('%H:%M:%S %d/%m/%Y') }}</li>
            <li class="list-group-item"><span class="font-weight-bold">Ссылка:</span> <a
                    href="{{ event.link }}">{{ event.link }}</a></li>
        </ul>
    </div>
{% endblock %}

services/web/app/templates/event/events.html
{% extends "base_template.html" %}

{% block title %} Пользователи {% endblock %}

{% block content %}
    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">События</li>
            </ol>
        </nav>
    </div>
    {% include 'widgets/flash_message.html' %}
    {% if current_user.get_role().name == 'ROLE_ADMIN' %}
        <div class="clearfix">
            <div class="float-left">
                <form class="form-inline">
                    <div class="form-group mr-1">
                        {% with placeholder = form.datetime_from.label.text %}
                            {{ form.datetime_from(class="form-control", placeholder=placeholder, type="datetime-local", step="1") }}
                        {% endwith %}
                    </div>
                    <div class="form-group mr-1">
                        {% with placeholder = form.datetime_to.label.text %}
                            {{ form.datetime_to(class="form-control", placeholder=placeholder, type="datetime-local", step="1") }}
                        {% endwith %}
                    </div>
                    {{ form.submit(class="btn btn-primary") }}
                </form>
            </div>
            {% if current_user.get_role().name == 'ROLE_ADMIN' %}
                <a role="button" href="{{ url_for('events.event_add') }}" class="btn btn-success float-right">Добавить
                    событие</a>
            {% endif %}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-7">
            <div class="w-100 mt-4 text-center">
                <table class="table table-bordered table-hover event-table">
                    <thead>
                    <tr class="table-active">
                        <th scope="col">ID</th>
                        <th scope="col">Пользователь</th>
                        <th scope="col">Событие</th>
                        <th scope="col">Время</th>
                        <th scope="col">Ссылка</th>
                        <th scope="col">Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events.items %}
                        <tr>
                            <th scope="row">{{ event.id }}</th>
                            <td>
                                {% if event.user %}
                                    <a href="{{ url_for('users.user_view', id=event.user.id) }}">{{ event.user }}</a>
                                {% else %}
                                    Неизвестный пользователь
                                {% endif %}
                            </td>
                            <td>{{ event.type_test() }}</td>
                            <td>{{ event.timestamp.strftime('%H:%M:%S %d/%m/%Y') }}</td>
                            <td><a href="{{ event.link }}">{{ event.link[:30] }}</a></td>
                            <td class="action">
                                <a href="{{ url_for('events.event_view', id=event.id) }}"><i class="fas fa-eye"></i></a>
                                {% if current_user.get_role().name == 'ROLE_ADMIN' or current_user.id == event.user.id %}
                                    <a href="{{ url_for('events.event_edit', id=event.id) }}"><i
                                            class="fas fa-edit"></i></a>
                                    <a href="{{ url_for('events.event_delete', id=event.id) }}"><i
                                            class="far fa-trash-alt"></i></a>
                                    <a href="#" class="play-btn" data-video="{{ event.link }}"><i
                                            class="fas fa-play"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="..." class="d-flex justify-content-center">
                    <ul class="pagination">
                        {% if events.has_prev %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('events.events', page = events.prev_num) }}"><<</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link"><<</span>
                            </li>
                        {% endif %}
                        {% if events.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('events.events', page = events.next_num) }}">>></a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">>></span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>
        </div>
        <div class="col-md-5">
            <div class="mt-4" id="video">
                <video controls width="100%">
                    <source src="" id="video-source">
                    <!-- MP4 для Safari, IE9, iPhone, iPad, Android, и Windows Phone 7 -->
                </video>
            </div>
        </div>
    </div>
{% endblock %}