services/web/app/cameras/__init__.py
from flask import Blueprint

bp = Blueprint('cameras', __name__)

from app.cameras import routes

services/web/app/cameras/routes.py
from app import db
from app.auth.decorators import role_required
from app.cameras import bp
from app.cameras.video_stream import VideoStream
from app.models import Camera, Role, Event
from flask import request, redirect, url_for, render_template, Response


@bp.route('/', methods=['GET'])
@bp.route('/main', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def main():
    events = Event.query.order_by(Event.timestamp.desc()).limit(5).all()
    event = Event.query.order_by(Event.timestamp.desc()).first()
    cameras_dict = {i: Camera.query.filter_by(position=i).filter_by(context=Camera.CONTEXT_MAIN_PAGE).first() for i in
                    range(1, 3)}
    return render_template('camera/main.html', cameras=cameras_dict, events=events, event=event)


@bp.route('/last-events', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def last_events():
    last_id = request.args.get("last_id", type=int)
    last_event = None
    if last_id:
        last_event = Event.query.get(last_id)
    events = Event.query.filter(Event.timestamp > last_event.timestamp) if last_event else Event.query
    event = Event.query.order_by(Event.timestamp.desc()).first()
    return render_template('camera/widgets/events-box.html', events=events.all(), event=event)


@bp.route('/cameras', methods=['GET', 'POST'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def cameras():
    cameras_dict = {i: Camera.query.filter_by(context=Camera.CONTEXT_CAMERAS).filter_by(position=i).first() for i in
                    range(1, 10)}
    return render_template('camera/camera.html', cameras=cameras_dict)


@bp.route('/camera/add/<string:context>', methods=['POST'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def add_camera(context):
    camera = Camera(link=request.form.get('link'), position=request.form.get('position'), context=context)
    db.session.add(camera)
    db.session.commit()
    url = url_for('cameras.cameras') if Camera.CONTEXT_CAMERAS == context else url_for('cameras.main')
    return redirect(url)


@bp.route('/camera/<int:id>/<string:context>', methods=['POST'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def edit_camera(id, context):
    camera = Camera.query.get_or_404(id)
    camera.link = request.form.get('link')
    db.session.commit()
    url = url_for('cameras.cameras') if Camera.CONTEXT_CAMERAS == context else url_for('cameras.main')
    return redirect(url)


@bp.route('/camera/<int:id>/delete/<string:context>', methods=['GET'])
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def delete_camera(id, context):
    camera = Camera.query.get_or_404(id)
    db.session.delete(camera)
    db.session.commit()
    url = url_for('cameras.cameras') if Camera.CONTEXT_CAMERAS == context else url_for('cameras.main')
    return redirect(url)


@bp.route('/camera/video_stream')
@role_required([Role.ROLE_ADMIN, Role.ROLE_SECRETARY])
def video_stream():
    stream = VideoStream(request.args.get('link'))
    return Response(stream.stream(), mimetype='multipart/x-mixed-replace; boundary=frame')

services/web/app/templates/camera/widgets/camera-box.html
{% if camera %}
    <div class="col video-stream-box">
        <div class="{% if camera_size == 'large' %}video-stream-large{% else %}video-stream-small{% endif %} video-stream-box-inner">
            <img class="video-stream-img"
                 src="{{ url_for('cameras.video_stream') }}?link={{ camera.link }}">
            <div class="mask">

                <a class="zoom" href="#" data-toggle="modal" data-target="#zooModal{{ key }}">
                    <i class="fas fa-search-plus fa-fw" aria-hidden="true"></i>
                </a>

                <a class="edit" href="#" data-toggle="modal" data-target="#editModal{{ key }}">
                    <i class="fas fa-edit fa-fw"></i>
                </a>
            </div>
        </div>
    </div>

    <div id="zooModal{{ key }}" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Просмотр камеры №{{ key }}</h4>
                    <button class="close" data-dismiss="modal">х</button>
                </div>
                <div class="modal-body">
                    <div>
                        <p><b>Ссылка:</b> <a href="{{ camera.link }}"> {{ camera.link }}</a></p>
                    </div>
                    <div class="zoom-video-stream-box">
                        <div class="zoom-video-stream-box-inner">
                            <img class="zoom-video-stream-img"
                                 src="{{ url_for('cameras.video_stream') }}?link={{ camera.link }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="editModal{{ key }}" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Редактирование камеры №{{ key }}</h4>
                    <button class="close" data-dismiss="modal">х</button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('cameras.edit_camera', id=camera.id, context=context) }}" method="POST">
                        <div class="form-group">
                            <label class="small mb-1" for="editInputLink">Ссылка</label>
                            <input class="form-control py-4" id="editInputLink" name="link" type="url"
                                   placeholder="Введите ссылку" autofocus="" required
                                   value="{{ camera.link }}"/>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Редактировать камеру</button>
                        <a href="{{ url_for('cameras.delete_camera', id=camera.id, context=context) }}"
                           class="mt-1 btn btn-danger w-100">Удалить камеру</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% else %}

    <div class="col video-stream-box">
        <div class="{% if camera_size == 'large' %}video-stream-large{% else %}video-stream-small{% endif %} video-stream-box-void">
            <a class="plus" href="#" data-toggle="modal" data-target="#addModal{{ key }}">
                <i class="fas fa-plus fa-fw"></i>
            </a>
        </div>
    </div>

    <div id="addModal{{ key }}" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Добавление новой камеры</h4>
                    <button class="close" data-dismiss="modal">х</button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('cameras.add_camera', context=context) }}" method="POST">
                        <input type="hidden" name="position" value="{{ key }}"/>
                        <div class="form-group">
                            <label class="small mb-1" for="inputLink">Ссылка</label>
                            <input class="form-control py-4" id="inputLink" name="link" type="url"
                                   placeholder="Введите ссылку" autofocus="" required/>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Добавить камеру</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endif %}

services/web/app/templates/camera/widgets/events-box.html
<div class="col" id="events-box">
    <div class="main-event-table-box">
        <table id="main-id-events" class="table table-bordered table-hover main-event-table">
            <thead>
            <tr class="table-active">
                <th scope="col">Пользователь</th>
                <th scope="col">Событие</th>
                <th scope="col">Время</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events|reverse %}
                <tr data-event-id="{{ event.id }}" class="line-event">
                    <td>
                        {% if event.user %}
                            <a href="{{ url_for('users.user_view', id=event.user.id) }}">{{ event.user }}</a>
                        {% else %}
                            Неизвестный пользователь
                        {% endif %}
                    </td>
                    <td>{{ event.type_test() }}</td>
                    <td>{{ event.timestamp.strftime('%H:%M:%S %d/%m/%Y') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="card mb-3 main-user-card-box">
        <div class="row no-gutters">
            <div class="col-md-5 main-user-card-img-inner">
                {% if event.user %}
                    <img src="{{ url_for('static', filename=event.user.avatar_image) }}" class="card-img">
                {% else %}
                    <img src="{{ url_for('static', filename=config['NO_IMAGE_FILE']) }}"
                         class="card-img">
                {% endif %}
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    {% if event %}
                        {% if event.user %}
                            <h3 class="card-title">{{ event.user.fio() }}</h3>
                            <h5 class="card-text mb-5"><b>Роль:</b> {{ event.user.get_role_name_ru() }}</h5>
                        {% else %}
                            <h3 class="card-title mb-5">Неизвестный пользователь</h3>
                        {% endif %}
                        {% if event.need_action() %}
                            <button type="button" class="btn btn-success">Открыть дверь</button>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>